name: Build
run-name: Build for [${{ inputs.service_name }}] by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "service to build"
        required: true
        type: choice
        options:
          - a-serivce
          - b-service
          - lib-service

env:
  JOBS: |
    '{
      "a-service": "cmd/a-service",
      "b-service": "cmd/b-service",
      "lib-service": "lib/cmd"
    }'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          dirs=${{ env.JOBS }}
          echo $dirs
          service_dir=$(echo $dirs | jq -r '."${{ inputs.service_name }}"')
          echo $service_dir

      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"

      - name: Build ${{ inputs.service_name }}
        run: |
          service_dir=$(echo ${{ env.JOBS }} | jq -r '."${{ inputs.service_name }}"')
          cd $service_dir
          go build -o amd64

      - name: Run ${{ inputs.service_name }}
        run: |
          cd $service_dir
          ./amd64
